# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node Console App

on:
  push:
    branches: [ main ]  
jobs:
  first-job:
    name: Buidl with Node
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x]
    steps:
      - run: node --version      
      - run: npm --version      
